layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 20
  exclude:
    archived: true
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 10564495
  # telegram: your_username
  twitter: portaalg
  # unsplash: your_username
  # vk: your_username
  website: http://daanbreur.systems
  youtube: channel/UCGWs9foruVqIoEf2sLBfJAg

topics:
  - name: NodeJS
    web_url: https://github.com/topics/node
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/nodejs/nodejs.png
  
  - name: HTML
    web_url: https://github.com/topics/html
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/html/html.png
  
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/javascript/javascript.png
    
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/css/css.png

languages:
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/javascript/javascript.png
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/python/python.png
