layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-feed

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 1000000
  exclude:
    archived: true
    forks: false
    projects:
    - portfolio
    - daanbreur

social_media:
  hackerrank: Daanbreur
  stackoverflow: 10564495
  twitter: portaalg
  website: http://daanbreur.systems
  youtube: channel/UCGWs9foruVqIoEf2sLBfJAg

topics:
  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/typescript/typescript.png
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/css/css.png
  - name: Flutter
    web_url: https://github.com/topics/flutter
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/flutter/flutter.png

languages:
  - name: NodeJS
    web_url: https://github.com/topics/node
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/nodejs/nodejs.png
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/javascript/javascript.png
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/python/python.png